# Generated by Django 5.2.3 on 2025-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
