# Generated by Django 5.2.3 on 2025-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
