# Generated by Django 5.2.3 on 2025-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_context_project_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.TextField(blank=True),
        ),
    ]
