# Generated by Django 5.2.3 on 2025-06-23 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=20)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=20)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
