# Generated by Django 5.2.3 on 2025-07-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_experience_order_number_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-order_number']},
        ),
    ]
